# Generated by Django 4.0 on 2022-03-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='content',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post2',
            name='profit',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
