# Generated by Django 4.0 on 2022-03-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post3_post4_post5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profit', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
